export const Adam_Sandler =()=>{
  return <img src="./Adam_Sandler.jpg" alt="adam"/>
}  

export const {anita_baker} = require("./anita_baker.jpg") 
export const {anuel_legends_never_die} = require("./anuel_legends_never_die.jpg") 
export const {avett_brothers_turnpike_troubadours} = require("./avett_brothers_turnpike_troubadours.jpg") 
export const {blink182} = require("./blink-182.jpg") 
export const {bruce_springsteen} = require("./bruce_springsteen.jpg") 
export const {Carrie_Underwood} = require("./Carrie_Underwood.jpg") 
export const {disney_on_ice_road_trip} = require("./disney_on_ice_road_trip.jpg") 
export const {disney_on_ice_road_trip_2} = require("./disney_on_ice_road_trip_2.jpg") 
export const {Harlem_Globetrotters} = require("./Harlem_Globetrotters.jpg") 
export const {MADONNA} = require("./MADONNA.jpg") 
export const {mana} = require("./mana.jpg") 
export const {MavericksvBulls} = require("./Mavericks-v-Bulls.jpg") 
export const {MavericksvGrizzlies} = require("./Mavericks-v-Grizzlies.jpg") 
export const {MavericksvHornets} = require("./Mavericks-v-Hornets.jpg") 
export const {MavericksvJazz} = require("./Mavericks-v-Jazz.jpg") 
export const {MavericksvKings} = require("./Mavericks-v-Kings.jpg") 
export const {MavericksvLakers} = require("./Mavericks-v-Lakers.jpg") 
export const {MavericksvPacers} = require("./Mavericks-v-Pacers.jpg") 
export const {MavericksvPredators} = require("./Mavericks-v-Predators.jpg") 
export const {MavericksvSixers} = require("./Mavericks-v-Sixers.jpg") 
export const {MavericksvSpurs} = require("./Mavericks-v-Spurs.jpg") 
export const {MavericksvSuns} = require("./Mavericks-v-Suns.jpg") 
export const {MavericksvTimberwolves} = require("./Mavericks-v-Timberwolves.jpg") 
export const {MavericksvWarriors} = require("./Mavericks-v-Warriors.jpg") 
export const {NCAAWomenBasketballTournamentFinalFour} = require("./NCAAWomenBasketballTournamentFinalFour.jpg") 
export const {StarsvAvalanche} = require("./Stars-v-Avalanche.jpg") 
export const {StarsvBlackhawks} = require("./Stars-v-Blackhawks.jpg") 
export const {StarsvBlueJackets} = require("./Stars-v-Blue-Jackets.jpg") 
export const {StarsvBlues} = require("./Stars-v-Blues.jpg") 
export const {StarsvBruins} = require("./Stars-v-Bruins.jpg") 
export const {StarsvCanucks} = require("./Stars-v-Canucks.jpg") 
export const {StarsvCoyotes} = require("./Stars-v-Coyotes.jpg") 
export const {StarsvFlames} = require("./Stars-v-Flames.jpg") 
export const {StarsvFlyers} = require("./Stars-v-Flyers.jpg") 
export const {StarsvKnights} = require("./Stars-v-Knights.jpg") 
export const {StarsvPeguins} = require("./Stars-v-Peguins.jpg") 
export const {StarsvPreds} = require("./Stars-v-Preds.jpg") 
export const {StarsvWild} = require("./Stars-v-Wild.jpg") 
export const {StarsvsKraken} = require("./Stars-vs-Kraken.jpg") 
export const {sza_sos_tour} = require("./sza_sos_tour.jpg") 
export const {TampaBayLightning} = require("./Tampa-Bay-Lightning.jpg") 
export const {thomas_rhett} = require("./thomas_rhett.jpg") 
