export const SET_MODAL_APPROVE_REQUEST = "SET_MODAL_APPROVE_REQUEST";
export const SET_APPROVE_REQUEST_MODAL_OPEN = "SET_APPROVE_REQUEST_MODAL_OPEN";
export const SET_APPROVE_REQUEST_MODAL_CLOSE = "SET_APPROVE_REQUEST_MODAL_CLOSE";
export const SET_MODAL_APPROVE_REQUEST_APPROVED = "SET_APPROVE_REQUEST_MODAL_CLOSE";