export const ADD_PUBLIC_EVENT="ADD_PUBLIC_EVENT"
export const REMOVE_PUBLIC_EVENT="REMOVE_PUBLIC_EVENT"

export const ADD_COMPANY_EVENT="ADD_COMPANY_EVENT"
export const REMOVE_COMPANY_EVENT="REMOVE_COMPANY_EVENT"
export const CHANGE_ACCESS_TYPE="CHANGE_ACCESS_TYPE"
