

export const POPULATE_EVENTS = "POPULATE_EVENTS";
export const POPULATE_PUBLIC_EVENTS = "POPULATE_PUBLIC_EVENTS";
export const ADJUST_SELECT_SEATS = "ADJUST_SELECT_SEATS";
export const ADJUST_OCC_SEATS = "ADJUST_OCC_SEATS";
export const LOAD_CURRENT_EVENT = "LOAD_CURRENT_EVENT"
export const SET_SELECTED_SEATS = "SET_SELECTED_SEATS"