export const SET_MODAL_REQUEST = "SET_MODAL_REQUEST";
export const SET_REQUEST_MODAL_OPEN = "SET_REQUEST_MODAL_OPEN";
export const SET_REQUEST_MODAL_CLOSE = "SET_REQUEST_MODAL_CLOSE";
export const SET_MODAL_REQUEST_APPROVED = "SET_MODAL_REQUEST_APPROVED";