export const SET_MODAL_EVENT = "SET_MODAL_EVENT";
export const SET_MODAL_OPEN = "SET_MODAL_OPEN";
export const SET_MODAL_CLOSE = "SET_MODAL_CLOSE";
export const SET_MODAL_EVENT_OCCUPIED = "SET_MODAL_EVENT_OCCUPIED";
export const RESET_MODAL_EVENT_OCCUPIED="RESET_MODAL_EVENT_OCCUPIED"

//
export const EDIT_EVENT_ACCESS_MODAL="EDIT_EVENT_ACCESS_MODAL"
export const EDIT_EVENT_ACCESS_TYPE="EDIT_EVENT_ACCESS_TYPE"
